using UnityEngine;

public class AllLevels : MonoBehaviour {

    public Block[][] levels = new Block[][] {
        new Block[] { // Level 1
            new Block(0, 0, BlockType.START),
            new Block(6, -5, BlockType.END),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(-1, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(7, -1),
            new Block(8, -1),
            new Block(7, -2),
            new Block(8, -2),
            new Block(7, -3),
            new Block(8, -3),
            new Block(7, -4),
            new Block(8, -4),
            new Block(7, -5),
            new Block(8, -5),
            new Block(7, -6),
            new Block(8, -6),
            new Block(5, -4),
            new Block(6, -4),
            new Block(5, -5),
            new Block(5, -6),
            new Block(6, -6),
        }, new Block[] { // Level 2
            new Block(0, 0, BlockType.START),
            new Block(1, 0, BlockType.END),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(7, -1),
            new Block(7, -2),
            new Block(7, -3),
            new Block(7, -4),
            new Block(7, -5),
            new Block(6, -4),
            new Block(6, -5),
            new Block(6, -6),
            new Block(6, -7),
            new Block(6, -8),
            new Block(6, -9),
            new Block(5, -9),
            new Block(4, -9),
            new Block(3, -9),
            new Block(3, -8),
            new Block(3, -7),
            new Block(3, -6),
            new Block(2, -6),
            new Block(1, -6),
            new Block(0, -6),
            new Block(0, -5),
            new Block(0, -4),
            new Block(0, -3),
            new Block(0, -2),
            new Block(0, -1),
            new Block(1, -1),
            new Block(-1, -1),
            new Block(-1, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
        },
        new Block[] { // Level 3
            new Block(0, 0, BlockType.START),
            new Block(0, -4, BlockType.END),
            new Block(-1, 0),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(3, -1),
            new Block(6, -1),
            new Block(9, -1),
            new Block(3, -2),
            new Block(6, -2),
            new Block(9, -2),
            new Block(3, -3),
            new Block(4, -3),
            new Block(5, -3),
            new Block(6, -3),
            new Block(9, -3),
            new Block(8, -4),
            new Block(9, -4),
            new Block(0, -5),
            new Block(1, -5),
            new Block(2, -5),
            new Block(3, -5),
            new Block(4, -5),
            new Block(5, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(0, -6),
            new Block(1, -6),
            new Block(2, -6),
            new Block(3, -6),
            new Block(4, -6),
            new Block(5, -6),
            new Block(6, -6),
            new Block(7, -6),
            new Block(8, -6),
            new Block(9, -6),
            new Block(7, -7),
            new Block(8, -7),
            new Block(9, -7),
            new Block(7, -8),
            new Block(8, -8),
        }, new Block[] { // Level 4
            new Block(0, 0, BlockType.START),
            new Block(10, 0, BlockType.END),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, 0),
            new Block(1, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(2, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0, BlockType.UNSTABLE_VERTICAL),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(3, -1),
            new Block(6, -1),
            new Block(9, -1),
            new Block(10, -1),
            new Block(0, -2),
            new Block(3, -2),
            new Block(6, -2),
            new Block(9, -2),
            new Block(10, -2),
            new Block(0, -3),
            new Block(1, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(2, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(6, -3),
            new Block(9, -3),
            new Block(0, -4),
            new Block(3, -4),
            new Block(6, -4),
            new Block(7, -4),
            new Block(8, -4),
            new Block(9, -4),
            new Block(0, -5),
            new Block(3, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(0, -6),
            new Block(1, -6),
            new Block(2, -6),
            new Block(3, -6),
        }, new Block[] { // Level 5
            new Block(0, 0, BlockType.START),
            new Block(0, -7, BlockType.END),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, 0),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(2, -1),
            new Block(3, -1),
            new Block(4, -1),
            new Block(5, -1),
            new Block(1, -2),
            new Block(2, -2),
            new Block(3, -2),
            new Block(5, -2),
            new Block(6, -2, BlockType.UNSTABLE_VERTICAL),
            new Block(5, -3),
            new Block(6, -3),
            new Block(7, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(8, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(9, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, -4),
            new Block(6, -4),
            new Block(7, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(8, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(9, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-1, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(-1, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -6, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -6),
            new Block(5, -6),
            new Block(9, -6),
            new Block(-1, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -7, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -7),
            new Block(5, -7),
            new Block(6, -7),
            new Block(9, -7),
            new Block(-1, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -8),
            new Block(5, -8),
            new Block(6, -8),
            new Block(7, -8),
            new Block(8, -8),
            new Block(9, -8),
            new Block(-1, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -9, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -9),
        }, new Block[] { // Level 6
            new Block(0, 0, BlockType.START),
            new Block(6, -6, BlockType.END),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0, BlockType.DISAPPEARING),
            new Block(4, 0),
            new Block(5, 0),
            new Block(4, -1),
            new Block(5, -1),
            new Block(1, -2),
            new Block(2, -2),
            new Block(3, -2, BlockType.DISAPPEARING),
            new Block(4, -2),
            new Block(5, -2),
            new Block(6, -2, BlockType.DISAPPEARING),
            new Block(7, -2),
            new Block(8, -2),
            new Block(7, -3),
            new Block(8, -3),
            new Block(3, -4),
            new Block(4, -4, BlockType.DISAPPEARING),
            new Block(5, -4, BlockType.DISAPPEARING),
            new Block(6, -4),
            new Block(7, -4),
            new Block(8, -4),
            new Block(4, -5, BlockType.DISAPPEARING),
            new Block(5, -5, BlockType.DISAPPEARING),
            new Block(3, -6),
            new Block(4, -6, BlockType.DISAPPEARING),
            new Block(5, -6, BlockType.DISAPPEARING),
        }, new Block[] { // Level 7
            new Block(0, 0, BlockType.START),
            new Block(-1, 0, BlockType.END),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0),
            new Block(10, 0),
            new Block(11, 0),
            new Block(9, 1),
            new Block(10, 1),
            new Block(11, 1),
            new Block(9, -1, BlockType.DISAPPEARING),
            new Block(10, -1, BlockType.DISAPPEARING),
            new Block(11, -1, BlockType.DISAPPEARING),
        }, new Block[] { // Level 8
            new Block(0, 0, BlockType.START),
            new Block(1, 0, BlockType.DISAPPEARING),
            new Block(2, 0, BlockType.DISAPPEARING),
            new Block(3, 0, BlockType.DISAPPEARING),
            new Block(4, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(6, 0, BlockType.DISAPPEARING),
            new Block(0, 3, BlockType.UNSTABLE_VERTICAL),
            new Block(1, 3, BlockType.DISAPPEARING),
            new Block(2, 3, BlockType.DISAPPEARING),
            new Block(3, 3, BlockType.DISAPPEARING),
            new Block(4, 3, BlockType.DISAPPEARING),
            new Block(5, 3, BlockType.DISAPPEARING),
            new Block(6, 3, BlockType.DISAPPEARING),
            new Block(0, -3, BlockType.END),
            new Block(1, -3, BlockType.DISAPPEARING),
            new Block(2, -3, BlockType.DISAPPEARING),
            new Block(3, -3, BlockType.DISAPPEARING),
            new Block(4, -3, BlockType.DISAPPEARING),
            new Block(5, -3, BlockType.DISAPPEARING),
            new Block(6, -3, BlockType.DISAPPEARING),
            new Block(0, 1, BlockType.DISAPPEARING),
            new Block(3, 1, BlockType.DISAPPEARING),
            new Block(6, 1, BlockType.DISAPPEARING),
            new Block(0, 2, BlockType.DISAPPEARING),
            new Block(3, 2, BlockType.DISAPPEARING),
            new Block(6, 2, BlockType.DISAPPEARING),
            new Block(0, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(6, -1, BlockType.DISAPPEARING),
            new Block(0, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(6, -2, BlockType.DISAPPEARING),
        }, new Block[] { // Level 9
            new Block(0, 0, BlockType.START),
            new Block(1, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0, BlockType.DISAPPEARING),
            new Block(0, -1),
            new Block(1, -1),
            new Block(2, -1),
            new Block(3, -1),
            new Block(5, -1),
            new Block(6, -1),
            new Block(0, -2),
            new Block(2, -2),
            new Block(3, -2),
            new Block(4, -2),
            new Block(5, -2, BlockType.END),
            new Block(6, -2),
            new Block(0, -3),
            new Block(1, -3),
            new Block(2, -3),
            new Block(3, -3, BlockType.DISAPPEARING),
            new Block(4, -3),
            new Block(5, -3),
            new Block(6, -3),
            new Block(0, -4),
            new Block(1, -4),
            new Block(2, -4),
            new Block(4, -4),
            new Block(5, -4),
            new Block(6, -4),
            new Block(0, -5),
            new Block(2, -5),
            new Block(3, -5),
            new Block(4, -5),
            new Block(5, -5),
            new Block(0, -6, BlockType.DISAPPEARING),
            new Block(1, -6),
            new Block(2, -6),
            new Block(3, -6),
            new Block(4, -6),
            new Block(5, -6),
        }, new Block[] { // Level 10
            new Block(5, 2),
            new Block(6, 2),
            new Block(12, 2),
            new Block(13, 2),
            new Block(14, 2),
            new Block(5, 1),
            new Block(6, 1),
            new Block(9, 1),
            new Block(10, 1),
            new Block(11, 1),
            new Block(12, 1),
            new Block(13, 1),
            new Block(14, 1),
            new Block(15, 1),
            new Block(16, 1),
            new Block(17, 1),
            new Block(18, 1),
            new Block(19, 1),
            new Block(0, 0, BlockType.START),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0, BlockType.DISAPPEARING),
            new Block(5, 0),
            new Block(6, 0),
            new Block(9, 0),
            new Block(12, 0),
            new Block(14, 0),
            new Block(19, 0),
            new Block(3, -1),
            new Block(5, -1),
            new Block(9, -1),
            new Block(11, -1),
            new Block(12, -1),
            new Block(14, -1),
            new Block(15, -1),
            new Block(16, -1),
            new Block(17, -1),
            new Block(18, -1),
            new Block(19, -1),
            new Block(3, -2),
            new Block(5, -2),
            new Block(9, -2),
            new Block(11, -2),
            new Block(12, -2),
            new Block(13, -2),
            new Block(14, -2),
            new Block(15, -2),
            new Block(16, -2),
            new Block(17, -2),
            new Block(18, -2),
            new Block(19, -2),
            new Block(0, -3),
            new Block(1, -3),
            new Block(2, -3, BlockType.DISAPPEARING),
            new Block(3, -3),
            new Block(4, -3, BlockType.DISAPPEARING),
            new Block(5, -3),
            new Block(6, -3),
            new Block(9, -3, BlockType.DISAPPEARING),
            new Block(11, -3, BlockType.DISAPPEARING),
            new Block(15, -3, BlockType.DISAPPEARING),
            new Block(18, -3),
            new Block(19, -3),
            new Block(0, -4),
            new Block(1, -4),
            new Block(6, -4, BlockType.DISAPPEARING),
            new Block(9, -4),
            new Block(10, -4, BlockType.DISAPPEARING),
            new Block(11, -4),
            new Block(12, -4),
            new Block(13, -4, BlockType.DISAPPEARING),
            new Block(14, -4),
            new Block(15, -4),
            new Block(16, -4, BlockType.END),
            new Block(17, -4, BlockType.DISAPPEARING),
            new Block(18, -4),
            new Block(19, -4),
            new Block(0, -5),
            new Block(1, -5),
            new Block(2, -5, BlockType.DISAPPEARING),
            new Block(6, -5),
            new Block(9, -5, BlockType.DISAPPEARING),
            new Block(11, -5, BlockType.DISAPPEARING),
            new Block(15, -5),
            new Block(18, -5),
            new Block(2, -6),
            new Block(4, -6),
            new Block(5, -6),
            new Block(6, -6),
            new Block(9, -6),
            new Block(11, -6),
            new Block(15, -6),
            new Block(16, -6),
            new Block(17, -6),
            new Block(18, -6),
            new Block(2, -7),
            new Block(4, -7),
            new Block(5, -7),
            new Block(6, -7),
            new Block(7, -7, BlockType.DISAPPEARING),
            new Block(8, -7, BlockType.DISAPPEARING),
            new Block(9, -7),
            new Block(11, -7),
            new Block(2, -8),
            new Block(9, -8),
            new Block(11, -8),
            new Block(2, -9),
            new Block(3, -9),
            new Block(4, -9),
            new Block(5, -9),
            new Block(6, -9),
            new Block(7, -9),
            new Block(8, -9),
            new Block(9, -9),
            new Block(10, -9),
            new Block(11, -9),
            new Block(2, -10),
            new Block(3, -10),
            new Block(4, -10),
            new Block(5, -10),
            new Block(6, -10),
            new Block(7, -10),
            new Block(8, -10),
            new Block(9, -10),
            new Block(10, -10),
            new Block(11, -10),
        }, new Block[] { // Level 11
            new Block(1, 3),
            new Block(2, 3),
            new Block(3, 3),
            new Block(4, 3),
            new Block(5, 3),
            new Block(6, 3),
            new Block(10, 3),
            new Block(11, 3),
            new Block(12, 3),
            new Block(13, 3),
            new Block(14, 3),
            new Block(15, 3),
            new Block(16, 3, BlockType.UNSTABLE_VERTICAL),
            new Block(19, 3),
            new Block(20, 3),
            new Block(21, 3),
            new Block(22, 3, BlockType.UNSTABLE_VERTICAL),
            new Block(23, 3),
            new Block(24, 3),
            new Block(25, 3),
            new Block(1, 2),
            new Block(2, 2),
            new Block(3, 2),
            new Block(4, 2),
            new Block(5, 2),
            new Block(6, 2),
            new Block(7, 2),
            new Block(10, 2),
            new Block(11, 2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(12, 2),
            new Block(13, 2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(14, 2),
            new Block(15, 2),
            new Block(16, 2),
            new Block(19, 2),
            new Block(20, 2),
            new Block(21, 2),
            new Block(24, 2),
            new Block(25, 2),
            new Block(1, 1),
            new Block(2, 1),
            new Block(4, 1),
            new Block(6, 1),
            new Block(7, 1),
            new Block(10, 1),
            new Block(11, 1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(12, 1),
            new Block(13, 1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(14, 1, BlockType.UNSTABLE_VERTICAL),
            new Block(15, 1),
            new Block(16, 1),
            new Block(19, 1),
            new Block(20, 1),
            new Block(21, 1),
            new Block(24, 1),
            new Block(25, 1),
            new Block(0, 0, BlockType.START),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0, BlockType.DISAPPEARING),
            new Block(9, 0, BlockType.DISAPPEARING),
            new Block(10, 0),
            new Block(11, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(12, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(13, 0),
            new Block(14, 0),
            new Block(15, 0),
            new Block(16, 0),
            new Block(17, 0, BlockType.DISAPPEARING),
            new Block(18, 0, BlockType.DISAPPEARING),
            new Block(19, 0),
            new Block(20, 0),
            new Block(21, 0),
            new Block(24, 0),
            new Block(25, 0),
            new Block(26, 0, BlockType.DISAPPEARING),
            new Block(27, 0, BlockType.DISAPPEARING),
            new Block(28, 0, BlockType.END),
            new Block(2, -1),
            new Block(4, -1),
            new Block(5, -1),
            new Block(6, -1),
            new Block(7, -1),
            new Block(10, -1),
            new Block(11, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(12, -1),
            new Block(13, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(14, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(15, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(19, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(20, -1),
            new Block(21, -1),
            new Block(22, -1),
            new Block(23, -1),
            new Block(24, -1),
            new Block(25, -1),
            new Block(1, -2),
            new Block(2, -2),
            new Block(3, -2),
            new Block(4, -2),
            new Block(5, -2),
            new Block(7, -2),
            new Block(10, -2),
            new Block(11, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(12, -2),
            new Block(13, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(14, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(15, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(16, -2),
            new Block(19, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(20, -2),
            new Block(21, -2),
            new Block(22, -2),
            new Block(23, -2),
            new Block(25, -2),
            new Block(1, -3),
            new Block(3, -3),
            new Block(4, -3),
            new Block(5, -3),
            new Block(6, -3),
            new Block(7, -3),
            new Block(10, -3),
            new Block(11, -3),
            new Block(12, -3),
            new Block(13, -3),
            new Block(14, -3),
            new Block(15, -3),
            new Block(16, -3),
            new Block(19, -3),
            new Block(20, -3),
            new Block(22, -3),
            new Block(23, -3),
            new Block(24, -3),
            new Block(25, -3),
        }, new Block[] { // Level 12
            new Block(0, 0, BlockType.START),
            new Block(-9, -5, BlockType.END),
            new Block(-4, 6),
            new Block(-3, 6),
            new Block(-2, 6),
            new Block(-1, 6),
            new Block(0, 6),
            new Block(-14, 5),
            new Block(-13, 5),
            new Block(-12, 5),
            new Block(-11, 5),
            new Block(-10, 5),
            new Block(-9, 5),
            new Block(-8, 5),
            new Block(-7, 5),
            new Block(-6, 5),
            new Block(-4, 5),
            new Block(-3, 5),
            new Block(0, 5),
            new Block(1, 5),
            new Block(2, 5),
            new Block(-14, 4),
            new Block(-7, 4),
            new Block(-6, 4),
            new Block(-5, 4),
            new Block(-4, 4),
            new Block(-3, 4),
            new Block(0, 4),
            new Block(1, 4),
            new Block(2, 4),
            new Block(-14, 3),
            new Block(-12, 3),
            new Block(-11, 3),
            new Block(-10, 3),
            new Block(-9, 3),
            new Block(2, 3),
            new Block(-14, 2),
            new Block(-12, 2),
            new Block(-9, 2),
            new Block(-6, 2),
            new Block(-5, 2),
            new Block(-4, 2),
            new Block(-3, 2),
            new Block(2, 2),
            new Block(3, 2),
            new Block(-14, 1),
            new Block(-12, 1),
            new Block(-9, 1),
            new Block(-6, 1),
            new Block(-3, 1),
            new Block(2, 1),
            new Block(3, 1),
            new Block(-14, 0),
            new Block(-12, 0),
            new Block(-9, 0),
            new Block(-8, 0),
            new Block(-7, 0),
            new Block(-6, 0, BlockType.DISAPPEARING),
            new Block(-5, 0),
            new Block(-4, 0),
            new Block(-3, 0, BlockType.DISAPPEARING),
            new Block(-2, 0),
            new Block(-1, 0),
            new Block(3, 0),
            new Block(-14, -1),
            new Block(-12, -1),
            new Block(-6, -1),
            new Block(-3, -1),
            new Block(3, -1),
            new Block(-14, -2),
            new Block(-12, -2),
            new Block(-6, -2),
            new Block(-3, -2),
            new Block(3, -2),
            new Block(-14, -3),
            new Block(-12, -3),
            new Block(-11, -3),
            new Block(-10, -3),
            new Block(-9, -3, BlockType.UNSTABLE_VERTICAL),
            new Block(-6, -3),
            new Block(-3, -3),
            new Block(-2, -3),
            new Block(-1, -3),
            new Block(0, -3),
            new Block(1, -3),
            new Block(2, -3),
            new Block(3, -3),
            new Block(-14, -4),
            new Block(-9, -4),
            new Block(-6, -4),
            new Block(-14, -5, BlockType.DISAPPEARING),
            new Block(-6, -5),
            new Block(-2, -5),
            new Block(-1, -5),
            new Block(0, -5),
            new Block(1, -5),
            new Block(2, -5),
            new Block(-14, -6),
            new Block(-13, -6),
            new Block(-12, -6),
            new Block(-9, -6),
            new Block(-6, -6),
            new Block(-5, -6),
            new Block(-4, -6),
            new Block(-3, -6),
            new Block(-2, -6),
            new Block(-1, -6),
            new Block(1, -6),
            new Block(2, -6),
            new Block(-14, -7),
            new Block(-13, -7),
            new Block(-12, -7),
            new Block(-9, -7),
            new Block(1, -7),
            new Block(2, -7),
            new Block(-14, -8),
            new Block(-13, -8),
            new Block(-12, -8),
            new Block(-11, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(-10, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(-9, -8),
            new Block(-8, -8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-7, -8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-6, -8),
            new Block(-5, -8),
            new Block(-4, -8),
            new Block(-3, -8),
            new Block(-2, -8),
            new Block(-1, -8),
            new Block(0, -8),
            new Block(1, -8),
            new Block(2, -8),
        }, new Block[] { // Level 13
            new Block(0, 0, BlockType.START),
            new Block(10, 5, BlockType.END),
            new Block(5, 5),
            new Block(6, 5),
            new Block(7, 5),
            new Block(8, 5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(9, 5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(11, 5),
            new Block(12, 5),
            new Block(13, 5),
            new Block(14, 5),
            new Block(15, 5),
            new Block(16, 5),
            new Block(17, 5),
            new Block(18, 5),
            new Block(5, 4),
            new Block(6, 4),
            new Block(7, 4),
            new Block(14, 4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(15, 4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(17, 4, BlockType.UNSTABLE_VERTICAL),
            new Block(18, 4, BlockType.UNSTABLE_VERTICAL),
            new Block(-1, 3),
            new Block(0, 3, BlockType.UNSTABLE_VERTICAL),
            new Block(1, 3, BlockType.UNSTABLE_VERTICAL),
            new Block(2, 3),
            new Block(3, 3),
            new Block(4, 3),
            new Block(5, 3),
            new Block(6, 3),
            new Block(7, 3),
            new Block(8, 3),
            new Block(9, 3),
            new Block(10, 3),
            new Block(14, 3),
            new Block(15, 3),
            new Block(16, 3),
            new Block(17, 3),
            new Block(18, 3),
            new Block(-1, 2),
            new Block(10, 2),
            new Block(13, 2),
            new Block(14, 2),
            new Block(15, 2),
            new Block(-6, 1),
            new Block(-5, 1),
            new Block(-4, 1),
            new Block(-3, 1),
            new Block(-1, 1),
            new Block(6, 1),
            new Block(7, 1),
            new Block(8, 1),
            new Block(10, 1),
            new Block(13, 1),
            new Block(-6, 0),
            new Block(-5, 0),
            new Block(-4, 0),
            new Block(-3, 0),
            new Block(-2, 0),
            new Block(-1, 0, BlockType.DISAPPEARING),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(10, 0),
            new Block(11, 0),
            new Block(12, 0),
            new Block(13, 0),
            new Block(-6, -1),
            new Block(-5, -1),
            new Block(-4, -1),
            new Block(-3, -1),
            new Block(-1, -1),
            new Block(2, -1),
            new Block(6, -1),
            new Block(7, -1),
            new Block(8, -1),
            new Block(11, -1),
            new Block(12, -1, BlockType.DISAPPEARING),
            new Block(13, -1, BlockType.DISAPPEARING),
            new Block(-1, -2),
            new Block(2, -2),
            new Block(11, -2),
            new Block(12, -2),
            new Block(13, -2),
            new Block(-1, -3),
            new Block(0, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(1, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(2, -3),
        }, new Block[] { // Level 14
            new Block(0, 0, BlockType.START),
            new Block(13, 1, BlockType.END),
            new Block(9, 1),
            new Block(10, 1),
            new Block(11, 1),
            new Block(14, 1),
            new Block(15, 1),
            new Block(16, 1),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0, BlockType.DISAPPEARING),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0),
            new Block(10, 0),
            new Block(11, 0),
            new Block(16, 0),
            new Block(9, -1, BlockType.UNSTABLE_HORIZONTAL),
            new Block(10, -1),
            new Block(11, -1),
            new Block(16, -1, BlockType.DISAPPEARING),
            new Block(10, -2),
            new Block(14, -2, BlockType.DISAPPEARING),
            new Block(15, -2),
            new Block(16, -2),
            new Block(2, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -3, BlockType.UNSTABLE_VERTICAL),
            new Block(5, -3, BlockType.UNSTABLE_VERTICAL),
            new Block(10, -3, BlockType.DISAPPEARING),
            new Block(14, -3),
            new Block(15, -3),
            new Block(16, -3),
            new Block(2, -4),
            new Block(3, -4),
            new Block(4, -4),
            new Block(5, -4),
            new Block(6, -4),
            new Block(7, -4),
            new Block(8, -4),
            new Block(9, -4),
            new Block(10, -4),
            new Block(14, -4),
            new Block(15, -4),
            new Block(16, -4),
            new Block(17, -4, BlockType.DISAPPEARING),
            new Block(18, -4),
            new Block(19, -4),
            new Block(2, -5),
            new Block(3, -5),
            new Block(4, -5),
            new Block(5, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(18, -5),
            new Block(19, -5),
            new Block(4, -6),
            new Block(10, -6),
            new Block(11, -6),
            new Block(12, -6),
            new Block(13, -6),
            new Block(14, -6, BlockType.DISAPPEARING),
            new Block(15, -6),
            new Block(16, -6),
            new Block(18, -6),
            new Block(19, -6),
            new Block(4, -7, BlockType.DISAPPEARING),
            new Block(10, -7),
            new Block(11, -7),
            new Block(12, -7),
            new Block(15, -7),
            new Block(16, -7),
            new Block(18, -7),
            new Block(19, -7),
            new Block(4, -8),
            new Block(5, -8),
            new Block(6, -8),
            new Block(7, -8),
            new Block(8, -8),
            new Block(9, -8),
            new Block(10, -8),
            new Block(11, -8),
            new Block(12, -8),
            new Block(15, -8),
            new Block(16, -8),
            new Block(17, -8, BlockType.DISAPPEARING),
            new Block(18, -8),
            new Block(19, -8),
        }, new Block[] { // Level 15
            new Block(0, 0, BlockType.START),
            new Block(7, 1, BlockType.END),
            new Block(-7, 8),
            new Block(-6, 8),
            new Block(-5, 8),
            new Block(-3, 8),
            new Block(-2, 8),
            new Block(-1, 8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(0, 8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(1, 8),
            new Block(2, 8),
            new Block(3, 8),
            new Block(5, 8),
            new Block(6, 8),
            new Block(7, 8),
            new Block(-7, 7, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-6, 7),
            new Block(-5, 7),
            new Block(-4, 7),
            new Block(-3, 7, BlockType.UNSTABLE_VERTICAL),
            new Block(-2, 7),
            new Block(-1, 7),
            new Block(0, 7),
            new Block(1, 7, BlockType.DISAPPEARING),
            new Block(2, 7),
            new Block(3, 7),
            new Block(4, 7),
            new Block(5, 7),
            new Block(7, 7),
            new Block(-7, 6, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-6, 6, BlockType.DISAPPEARING),
            new Block(-5, 6),
            new Block(-4, 6),
            new Block(-3, 6),
            new Block(-2, 6),
            new Block(-1, 6),
            new Block(0, 6),
            new Block(1, 6),
            new Block(2, 6),
            new Block(4, 6),
            new Block(5, 6),
            new Block(6, 6),
            new Block(7, 6),
            new Block(-7, 5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-6, 5, BlockType.DISAPPEARING),
            new Block(-5, 5),
            new Block(-4, 5),
            new Block(-3, 5),
            new Block(-1, 5),
            new Block(1, 5),
            new Block(2, 5),
            new Block(3, 5),
            new Block(4, 5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, 5,BlockType.DISAPPEARING),
            new Block(6, 5),
            new Block(7, 5),
            new Block(-7, 4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-5, 4),
            new Block(-4, 4, BlockType.DISAPPEARING),
            new Block(-3, 4),
            new Block(-2, 4),
            new Block(-1, 4),
            new Block(0, 4),
            new Block(1, 4),
            new Block(3, 4),
            new Block(4, 4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, 4),
            new Block(6, 4),
            new Block(7, 4),
            new Block(-7, 3),
            new Block(-6, 3),
            new Block(-5, 3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-4, 3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-2, 3),
            new Block(-1, 3),
            new Block(0, 3),
            new Block(1, 3),
            new Block(2, 3),
            new Block(3, 3),
            new Block(5, 3),
            new Block(7, 3),
            new Block(-7, 2),
            new Block(-6, 2),
            new Block(-5, 2),
            new Block(-4, 2),
            new Block(-3, 2),
            new Block(-2, 2),
            new Block(-1, 2, BlockType.DISAPPEARING),
            new Block(0, 2),
            new Block(2, 2),
            new Block(3, 2),
            new Block(4, 2),
            new Block(5, 2),
            new Block(6, 2),
            new Block(-7, 1),
            new Block(-6, 1, BlockType.UNSTABLE_VERTICAL),
            new Block(-5, 1),
            new Block(-3, 1, BlockType.UNSTABLE_VERTICAL),
            new Block(-2, 1),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(2, 1),
            new Block(3, 1, BlockType.UNSTABLE_VERTICAL),
            new Block(4, 1),
            new Block(5, 1),
            new Block(6, 1, BlockType.DISAPPEARING),
            new Block(-6, 0),
            new Block(-5, 0),
            new Block(-4, 0),
            new Block(-3, 0),
            new Block(-2, 0),
            new Block(-1, 0),
            new Block(1, 0),
            new Block(2, 0),
            new Block(4, 0, BlockType.UNSTABLE_VERTICAL),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(-7, -1, BlockType.DISAPPEARING),
            new Block(-6, -1),
            new Block(-5, -1),
            new Block(-4, -1),
            new Block(-2, -1),
            new Block(-1, -1, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -1),
            new Block(1, -1),
            new Block(2, -1),
            new Block(3, -1),
            new Block(4, -1),
            new Block(6, -1),
            new Block(7, -1),
            new Block(-7, -2),
            new Block(-6, -2),
            new Block(-4, -2),
            new Block(-3, -2),
            new Block(-2, -2),
            new Block(-1, -2),
            new Block(0, -2),
            new Block(1, -2, BlockType.DISAPPEARING),
            new Block(2, -2),
            new Block(3, -2),
            new Block(4, -2, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, -2),
            new Block(7, -2),
            new Block(-7, -3),
            new Block(-6, -3),
            new Block(-5, -3),
            new Block(-4, -3),
            new Block(-3, -3),
            new Block(-2, -3),
            new Block(0, -3),
            new Block(1, -3),
            new Block(2, -3),
            new Block(4, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, -3),
            new Block(6, -3),
            new Block(7, -3, BlockType.UNSTABLE_VERTICAL),
            new Block(-7, -4),
            new Block(-6, -4, BlockType.DISAPPEARING),
            new Block(-4, -4),
            new Block(-2, -4),
            new Block(-1, -4),
            new Block(1, -4),
            new Block(2, -4),
            new Block(3, -4),
            new Block(4, -4),
            new Block(6, -4),
            new Block(7, -4),
            new Block(-7, -5),
            new Block(-6, -5),
            new Block(-4, -5),
            new Block(-3, -5),
            new Block(-2, -5),
            new Block(-1, -5),
            new Block(0, -5),
            new Block(2, -5),
            new Block(3, -5),
            new Block(4, -5),
            new Block(5, -5),
            new Block(6, -5, BlockType.DISAPPEARING),
            new Block(7, -5),
            new Block(-7, -6),
            new Block(-5, -6),
            new Block(-4, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(-3, -6),
            new Block(-2, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(-1, -6),
            new Block(0, -6),
            new Block(2, -6),
            new Block(4, -6),
            new Block(5, -6),
            new Block(6, -6),
            new Block(7, -6),
            new Block(-7, -7),
            new Block(-6, -7, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-5, -7, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-4, -7),
            new Block(-3, -7),
            new Block(-1, -7),
            new Block(0, -7, BlockType.DISAPPEARING),
            new Block(1, -7),
            new Block(2, -7),
            new Block(3, -7),
            new Block(4, -7),
            new Block(5, -7),
            new Block(6, -7),
            new Block(7, -7),
        }
    };

    public class Block {
        public int x;
        public int y;
        public BlockType type;

        public Block(int x, int y) {
            this.x = x;
            this.y = y;
            type = BlockType.STANDARD;
        }

        public Block(int x, int y, BlockType type) {
            this.x = x;
            this.y = y;
            this.type = type;
        }

        public string getName() {
            return "Block(" + x + ", " + y + ")";
        }
    }

    public enum BlockType {
        START,
        STANDARD,
        END,
        DISAPPEARING,
        UNSTABLE_HORIZONTAL,
        UNSTABLE_VERTICAL
    }
}
