using UnityEngine;

public class AllLevels : MonoBehaviour {

    public Block[][] levels = new Block[][] {
        new Block[] { // Level 1
            new Block(0, 0, BlockType.START),
            new Block(6, -5, BlockType.END),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(-1, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(7, -1),
            new Block(8, -1),
            new Block(7, -2),
            new Block(8, -2),
            new Block(7, -3),
            new Block(8, -3),
            new Block(7, -4),
            new Block(8, -4),
            new Block(7, -5),
            new Block(8, -5),
            new Block(7, -6),
            new Block(8, -6),
            new Block(5, -4),
            new Block(6, -4),
            new Block(5, -5),
            new Block(5, -6),
            new Block(6, -6),
        }, new Block[] { // Level 2
            new Block(0, 0, BlockType.START),
            new Block(1, 0, BlockType.END),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(7, -1),
            new Block(7, -2),
            new Block(7, -3),
            new Block(7, -4),
            new Block(7, -5),
            new Block(6, -4),
            new Block(6, -5),
            new Block(6, -6),
            new Block(6, -7),
            new Block(6, -8),
            new Block(6, -9),
            new Block(5, -9),
            new Block(4, -9),
            new Block(3, -9),
            new Block(3, -8),
            new Block(3, -7),
            new Block(3, -6),
            new Block(2, -6),
            new Block(1, -6),
            new Block(0, -6),
            new Block(0, -5),
            new Block(0, -4),
            new Block(0, -3),
            new Block(0, -2),
            new Block(0, -1),
            new Block(1, -1),
            new Block(-1, -1),
            new Block(-1, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
        },
        new Block[] { // Level 3
            new Block(0, 0, BlockType.START),
            new Block(0, -4, BlockType.END),
            new Block(-1, 0),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(3, -1),
            new Block(6, -1),
            new Block(9, -1),
            new Block(3, -2),
            new Block(6, -2),
            new Block(9, -2),
            new Block(3, -3),
            new Block(4, -3),
            new Block(5, -3),
            new Block(6, -3),
            new Block(9, -3),
            new Block(8, -4),
            new Block(9, -4),
            new Block(0, -5),
            new Block(1, -5),
            new Block(2, -5),
            new Block(3, -5),
            new Block(4, -5),
            new Block(5, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(0, -6),
            new Block(1, -6),
            new Block(2, -6),
            new Block(3, -6),
            new Block(4, -6),
            new Block(5, -6),
            new Block(6, -6),
            new Block(7, -6),
            new Block(8, -6),
            new Block(9, -6),
            new Block(7, -7),
            new Block(8, -7),
            new Block(9, -7),
            new Block(7, -8),
            new Block(8, -8),
        }, new Block[] { // Level 4
            new Block(0, 0, BlockType.START),
            new Block(10, 0, BlockType.END),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, 0),
            new Block(1, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(2, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, 0, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, 0),
            new Block(5, 0),
            new Block(6, 0),
            new Block(7, 0),
            new Block(8, 0),
            new Block(9, 0, BlockType.UNSTABLE_VERTICAL),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(3, -1),
            new Block(6, -1),
            new Block(9, -1),
            new Block(10, -1),
            new Block(0, -2),
            new Block(3, -2),
            new Block(6, -2),
            new Block(9, -2),
            new Block(10, -2),
            new Block(0, -3),
            new Block(1, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(2, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(3, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(6, -3),
            new Block(9, -3),
            new Block(0, -4),
            new Block(3, -4),
            new Block(6, -4),
            new Block(7, -4),
            new Block(8, -4),
            new Block(9, -4),
            new Block(0, -5),
            new Block(3, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(0, -6),
            new Block(1, -6),
            new Block(2, -6),
            new Block(3, -6),
        }, new Block[] { // Level 5
            new Block(0, 0, BlockType.START),
            new Block(0, -7, BlockType.END),
            new Block(-1, 1),
            new Block(0, 1),
            new Block(1, 1),
            new Block(-1, 0),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0),
            new Block(4, 0),
            new Block(5, 0),
            new Block(-1, -1),
            new Block(0, -1),
            new Block(1, -1),
            new Block(2, -1),
            new Block(3, -1),
            new Block(4, -1),
            new Block(5, -1),
            new Block(1, -2),
            new Block(2, -2),
            new Block(3, -2),
            new Block(5, -2),
            new Block(6, -2, BlockType.UNSTABLE_VERTICAL),
            new Block(5, -3),
            new Block(6, -3),
            new Block(7, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(8, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(9, -3, BlockType.UNSTABLE_HORIZONTAL),
            new Block(5, -4),
            new Block(6, -4),
            new Block(7, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(8, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(9, -4, BlockType.UNSTABLE_HORIZONTAL),
            new Block(-1, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -5, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -5, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -5),
            new Block(6, -5),
            new Block(7, -5),
            new Block(8, -5),
            new Block(9, -5),
            new Block(-1, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -6, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -6, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -6),
            new Block(5, -6),
            new Block(9, -6),
            new Block(-1, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -7, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -7, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -7),
            new Block(5, -7),
            new Block(6, -7),
            new Block(9, -7),
            new Block(-1, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -8, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -8, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -8),
            new Block(5, -8),
            new Block(6, -8),
            new Block(7, -8),
            new Block(8, -8),
            new Block(9, -8),
            new Block(-1, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(0, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(1, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(2, -9, BlockType.UNSTABLE_VERTICAL),
            new Block(3, -9, BlockType.UNSTABLE_HORIZONTAL),
            new Block(4, -9),
        }, new Block[] { // Level 6
            new Block(0, 0, BlockType.START),
            new Block(6, -6, BlockType.END),
            new Block(1, 0),
            new Block(2, 0),
            new Block(3, 0, BlockType.DISAPPEARING),
            new Block(4, 0),
            new Block(5, 0),
            new Block(4, -1),
            new Block(5, -1),
            new Block(1, -2),
            new Block(2, -2),
            new Block(3, -2, BlockType.DISAPPEARING),
            new Block(4, -2),
            new Block(5, -2),
            new Block(6, -2, BlockType.DISAPPEARING),
            new Block(7, -2),
            new Block(8, -2),
            new Block(7, -3),
            new Block(8, -3),
            new Block(3, -4),
            new Block(4, -4, BlockType.DISAPPEARING),
            new Block(5, -4, BlockType.DISAPPEARING),
            new Block(6, -4),
            new Block(7, -4),
            new Block(8, -4),
            new Block(4, -5, BlockType.DISAPPEARING),
            new Block(5, -5, BlockType.DISAPPEARING),
            new Block(3, -6),
            new Block(4, -6, BlockType.DISAPPEARING),
            new Block(5, -6, BlockType.DISAPPEARING),
        }
    };

    public class Block {
        public int x;
        public int y;
        public BlockType type;

        public Block(int x, int y) {
            this.x = x;
            this.y = y;
            type = BlockType.STANDARD;
        }

        public Block(int x, int y, BlockType type) {
            this.x = x;
            this.y = y;
            this.type = type;
        }

        public string getName() {
            return "Block(" + x + ", " + y + ")";
        }
    }

    public enum BlockType {
        START,
        STANDARD,
        END,
        DISAPPEARING,
        UNSTABLE_HORIZONTAL,
        UNSTABLE_VERTICAL
    }
}
